const EXPENSE_CATEGORIES = {
    FOOD: 'FOOD',
    SOCIAL_LIFE: 'SOCIAL_LIFE',
    SELF_DEVELOPMENT: 'SELF_DEVELOPMENT',
    TRANSPORTATION: 'TRANSPORTATION',
    CULTURE: 'CULTURE',
    HOUSEHOLD: 'HOUSEHOLD',
    APPAREL: 'APPAREL',
    BEAUTY: 'BEAUTY',
    HEALTH: 'HEALTH',
    EDUCATION: 'EDUCATION',
    GIFT: 'GIFT',
    OTHER: 'OTHER'
}

module.exports = EXPENSE_CATEGORIES